# Tugas 1 - Menghitung Jarak

Tugas mengukur jarak (dissimilarity)
1. ambil data dari kaggle atau github
2. ukur jarak d(1,2), d(1,3), d(1,4) dari data tersebut

In [41]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# import library
import numpy as np
import pandas as pd
import seaborn as sns
%matplotlib inline
import matplotlib.pyplot as plt
import math

In [ ]:
# import file dengan code
import pandas as pd
from google.colab import files
file = files.upload()

Saving housePrice.csv to housePrice (1).csv

In [ ]:
#menampilkan data
dt = pd.read_csv("https://raw.githubusercontent.com/AliGhufron-28/datamaining/main/HousingPrices-Amsterdam-August-2021.csv")
print(dt)

     Unnamed: 0                                 Address      Zip     Price  \
0             1            Blasiusstraat 8 2, Amsterdam  1091 CR  685000.0
1             2  Kromme Leimuidenstraat 13 H, Amsterdam  1059 EL  475000.0
2             3              Zaaiersweg 11 A, Amsterdam  1097 SM  850000.0
3             4            Tenerifestraat 40, Amsterdam  1060 TH  580000.0
4             5              Winterjanpad 21, Amsterdam  1036 KN  720000.0
..          ...                                     ...      ...       ...
919         920                     Ringdijk, Amsterdam  1097 AE  750000.0
920         921         Kleine Beerstraat 31, Amsterdam  1033 CP  350000.0
921         922       Stuyvesantstraat 33 II, Amsterdam  1058 AK  350000.0
922         923   John Blankensteinstraat 51, Amsterdam  1095 MB  599000.0
923         924      S. F. van Ossstraat 334, Amsterdam  1068 JS  300000.0

     Area  Room       Lon        Lat
0      64     3  4.907736  52.356157
1      60     3  4.850476  52.348586
2     109     4  4.944774  52.343782
3     128     6  4.789928  52.343712
4     138     5  4.902503  52.410538
..    ...   ...       ...        ...
919   117     1  4.927757  52.354173
920    72     3  4.890612  52.414587
921    51     3  4.856935  52.363256
922   113     4  4.965731  52.375268
923    79     4  4.810678  52.355493

[924 rows x 8 columns]

In [ ]:
dt.head()

,Unnamed: 0,Address,Zip,Price,Area,Room,Lon,Lat
0,1,"Blasiusstraat 8 2, Amsterdam",1091 CR,685000.0,64,3,4.907736,52.356157
1,2,"Kromme Leimuidenstraat 13 H, Amsterdam",1059 EL,475000.0,60,3,4.850476,52.348586
2,3,"Zaaiersweg 11 A, Amsterdam",1097 SM,850000.0,109,4,4.944774,52.343782
3,4,"Tenerifestraat 40, Amsterdam",1060 TH,580000.0,128,6,4.789928,52.343712
4,5,"Winterjanpad 21, Amsterdam",1036 KN,720000.0,138,5,4.902503,52.410538

In [ ]:
# Proximity Measure for Nominal Attributes
def d1(i,j):
    P = 2
    Q = 0
    for col in ["Address","Zip"]:
        if dt[col][i] == dt[col][j]:
            Q += 1
    return (P-Q)/P

In [ ]:
print(d1(1,2))
print(d1(1,3))
print(d1(1,4))

1.0
1.0
1.0

In [ ]:
# Distance on Numeric Data: Minkowski Distance
def d2(i,j, h):
    result = 0
    for col in ["Price","Area","Room","Lon","Lat"]:
        result = math.pow(abs(dt[col][i] - dt[col][j]), h)
    return result**(1/h)

In [ ]:
# Manhattan distance
print(d2(1,2,1))
print(d2(1,3,1))
print(d2(1,4,1))

0.0048040000000000305
0.004874000000000933
0.061952000000005114

In [ ]:
# Euclidean distance
print(d2(1,2,2))
print(d2(1,3,2))
print(d2(1,4,2))

0.0048040000000000305
0.004874000000000933
0.061952000000005114

Disimilarity

In [ ]:
# d(1,2)
print(d1(1,2)+d2(1,2,1))

1.004804

In [ ]:
# d(1,3)
print(d1(1,3)+d2(1,3,1))

1.004874000000001

In [ ]:
# d(1,4)
print(d1(1,4)+d2(1,4,1))

1.0619520000000051