# Tugas 1 - Menghitung Jarak

Tugas mengukur jarak (dissimilarity)
1. ambil data dari kaggle atau github
2. ukur jarak d(1,2), d(1,3), d(1,4) dari data tersebut

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# import library
import numpy as np
import pandas as pd
import seaborn as sns
%matplotlib inline
import matplotlib.pyplot as plt
import math

In [ ]:
# import file dengan code
import pandas as pd
from google.colab import files
file = files.upload()

Saving housePrice.csv to housePrice (1).csv

In [ ]:
#menampilkan data
dt = pd.read_csv("https://raw.githubusercontent.com/AliGhufron-28/datamaining/main/HousingPrices-Amsterdam-August-2021.csv")
print(dt)

     Unnamed: 0                                 Address      Zip     Price  \
0             1            Blasiusstraat 8 2, Amsterdam  1091 CR  685000.0
1             2  Kromme Leimuidenstraat 13 H, Amsterdam  1059 EL  475000.0
2             3              Zaaiersweg 11 A, Amsterdam  1097 SM  850000.0
3             4            Tenerifestraat 40, Amsterdam  1060 TH  580000.0
4             5              Winterjanpad 21, Amsterdam  1036 KN  720000.0
..          ...                                     ...      ...       ...
919         920                     Ringdijk, Amsterdam  1097 AE  750000.0
920         921         Kleine Beerstraat 31, Amsterdam  1033 CP  350000.0
921         922       Stuyvesantstraat 33 II, Amsterdam  1058 AK  350000.0
922         923   John Blankensteinstraat 51, Amsterdam  1095 MB  599000.0
923         924      S. F. van Ossstraat 334, Amsterdam  1068 JS  300000.0

     Area  Room       Lon        Lat
0      64     3  4.907736  52.356157
1      60     3  4.850476  52.348586
2     109     4  4.944774  52.343782
3     128     6  4.789928  52.343712
4     138     5  4.902503  52.410538
..    ...   ...       ...        ...
919   117     1  4.927757  52.354173
920    72     3  4.890612  52.414587
921    51     3  4.856935  52.363256
922   113     4  4.965731  52.375268
923    79     4  4.810678  52.355493

[924 rows x 8 columns]

In [ ]:
dt.head()

,Unnamed: 0,Address,Zip,Price,Area,Room,Lon,Lat
0,1,"Blasiusstraat 8 2, Amsterdam",1091 CR,685000.0,64,3,4.907736,52.356157
1,2,"Kromme Leimuidenstraat 13 H, Amsterdam",1059 EL,475000.0,60,3,4.850476,52.348586
2,3,"Zaaiersweg 11 A, Amsterdam",1097 SM,850000.0,109,4,4.944774,52.343782
3,4,"Tenerifestraat 40, Amsterdam",1060 TH,580000.0,128,6,4.789928,52.343712
4,5,"Winterjanpad 21, Amsterdam",1036 KN,720000.0,138,5,4.902503,52.410538

In [ ]:
# Proximity Measure for Nominal Attributes
def d1(i,j):
    P = 2
    Q = 0
    for col in ["Address","Zip"]:
        if dt[col][i] == dt[col][j]:
            Q += 1
    return (P-Q)/P

In [ ]:
print(d1(1,2))
print(d1(1,3))
print(d1(1,4))

1.0
1.0
1.0

In [ ]:
# Distance on Numeric Data: Minkowski Distance
def d2(i,j, h):
    result = 0
    for col in ["Price","Area","Room","Lon","Lat"]:
        result = math.pow(abs(dt[col][i] - dt[col][j]), h)
    return result**(1/h)

In [ ]:
# Manhattan distance
print(d2(1,2,1))
print(d2(1,3,1))
print(d2(1,4,1))

0.0048040000000000305
0.004874000000000933
0.061952000000005114

In [ ]:
# Euclidean distance
print(d2(1,2,2))
print(d2(1,3,2))
print(d2(1,4,2))

0.0048040000000000305
0.004874000000000933
0.061952000000005114

Disimilarity

In [ ]:
# d(1,2)
print(d1(1,2)+d2(1,2,1))

1.004804

In [ ]:
# d(1,3)
print(d1(1,3)+d2(1,3,1))

1.004874000000001

In [ ]:
# d(1,4)
print(d1(1,4)+d2(1,4,1))

1.0619520000000051

# Tugas 2 - Diskritisasi

1. mencari nilai equel width
2. mencari nilai equel frekuensi
3. entropy

- Equel Width

In [ ]:
# import library
import pandas as pd
import math
from sklearn import datasets

In [ ]:
# membaca dataset
dt_iris = pd.read_csv("https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv")
print(dt_iris)

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [ ]:
dt_iris.head(10)

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           1.4          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa

In [ ]:
# CONSTAN SERIES

SEPAL_LENGTH_SERIES = dt_iris["sepal.length"]
SEPAL_WIDTH_SERIES = dt_iris["sepal.width"]
PETAL_LENGTH_SERIES = dt_iris["petal.length"]
PETAL_WIDTH_SERIES = dt_iris["petal.width"]

In [ ]:
# equal-width intervals

labels = ["Sedikit Lebar", "Lebar", "Sangat Lebar"]
amount_of_binning = len(labels)

sepal_width_ew_binning = pd.cut(SEPAL_WIDTH_SERIES, amount_of_binning, True, labels)
labelled_sepal_width_ew_binning = sepal_width_ew_binning.value_counts()
interval_sepal_width_ew_binning = pd.cut(SEPAL_WIDTH_SERIES, amount_of_binning, True).value_counts()

In [ ]:
# dataframe of sepal-width and sepal category
pd.concat((SEPAL_WIDTH_SERIES, sepal_width_ew_binning), axis=1)

In [ ]:
# equal-width intervals binning with label
labelled_sepal_width_ew_binning

In [ ]:
# equal-width intervals without label
interval_sepal_width_ew_binning

In [ ]:
# mengetahui jumlah baris dan kolom
dt_iris.shape

(150, 5)

In [ ]:
# Proses diskritisasi sepal_length
from sklearn.preprocessing import KBinsDiscretizer
est = KBinsDiscretizer(n_bins=4,
                       encode='ordinal', 
                       strategy='uniform')
dt_iris["sepal.length"] = est.fit_transform(dt_iris[["sepal.length"]])

In [ ]:
# Menampilkan hasil dari diskritisasi dari sepal_length
dt_iris["sepal.length"]

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
145    2.0
146    2.0
147    2.0
148    2.0
149    1.0
Name: sepal.length, Length: 150, dtype: float64

In [ ]:
# Proses diskritisasi sepal_width
from sklearn.preprocessing import KBinsDiscretizer
est = KBinsDiscretizer(n_bins=4,
                       encode='ordinal', 
                       strategy='uniform')
dt_iris["sepal.width"] = est.fit_transform(dt_iris[["sepal.width"]])

In [ ]:
# Menampilkan hasil dari diskritisasi dari sepal_width
dt_iris["sepal.width"]

0      2.0
1      1.0
2      2.0
3      1.0
4      2.0
      ...
145    1.0
146    0.0
147    1.0
148    2.0
149    1.0
Name: sepal.width, Length: 150, dtype: float64

In [ ]:
# Proses diskritisasi petal.length
from sklearn.preprocessing import KBinsDiscretizer
est = KBinsDiscretizer(n_bins=4,
                       encode='ordinal', 
                       strategy='uniform')
dt_iris["petal.length"] = est.fit_transform(dt_iris[["petal.length"]])

In [ ]:
dt_iris["petal.length"]

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
145    2.0
146    2.0
147    2.0
148    2.0
149    2.0
Name: petal.length, Length: 150, dtype: float64

In [ ]:
# Proses diskritisasi petal.width
from sklearn.preprocessing import KBinsDiscretizer
est = KBinsDiscretizer(n_bins=4,
                       encode='ordinal', 
                       strategy='uniform')
dt_iris["petal.width"] = est.fit_transform(dt_iris[["petal.width"]])

In [ ]:
dt_iris["petal.width"]

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
145    3.0
146    3.0
147    3.0
148    3.0
149    2.0
Name: petal.width, Length: 150, dtype: float64

- Equel Frequensy

- Qcut adalah sebuah method pada library pandas untuk melakukan perhitungan equal frequency intervals

In [ ]:
import pandas as pd

In [ ]:
# CONSTAN SERIES

SEPAL_LENGTH_SERIES = dt_iris["sepal.length"]
SEPAL_WIDTH_SERIES = dt_iris["sepal.width"]
PETAL_LENGTH_SERIES = dt_iris["petal.length"]
PETAL_WIDTH_SERIES = dt_iris["petal.width"]

In [ ]:
# equal-frequency intervals

labels = ["Sedikit Lebar", "Lebar", "Sangat Lebar"]
amount_of_binning = len(labels)

sepal_width_ef_binning = pd.qcut(SEPAL_WIDTH_SERIES, amount_of_binning, labels)
labelled_sepal_width_ef_binning = sepal_width_ef_binning.value_counts()
interval_sepal_width_ef_binning = pd.qcut(SEPAL_WIDTH_SERIES, amount_of_binning).value_counts()

In [ ]:
# dataframe of sepal-width and sepal category
pd.concat((SEPAL_WIDTH_SERIES, sepal_width_ef_binning), axis = 1)

    sepal.width    sepal.width
0           3.5   Sangat Lebar
1           3.0          Lebar
2           3.2          Lebar
3           3.1          Lebar
4           3.6   Sangat Lebar
..          ...            ...
145         3.0          Lebar
146         2.5  Sedikit Lebar
147         3.0          Lebar
148         3.4   Sangat Lebar
149         3.0          Lebar

[150 rows x 2 columns]

In [ ]:
# equal-frequency intervals binning with label
labelled_sepal_width_ef_binning

Sedikit Lebar    57
Lebar            50
Sangat Lebar     43
Name: sepal.width, dtype: int64

In [ ]:
# equal-frequency intervals out label
interval_sepal_width_ef_binning

(1.999, 2.9]    57
(2.9, 3.2]      50
(3.2, 4.4]      43
Name: sepal.width, dtype: int64

In [ ]:
# petal width
# equal-frequency intervals

labels = ["Sedikit Lebar", "Lebar", "Sangat Lebar"]
amount_of_binning = len(labels)

petal_width_ef_binning = pd.qcut(PETAL_WIDTH_SERIES, amount_of_binning, labels)
labelled_petal_width_ef_binning = petal_width_ef_binning.value_counts()
interval_petal_width_ef_binning = pd.qcut(PETAL_WIDTH_SERIES, amount_of_binning).value_counts()

In [ ]:
# dataframe of petal-width and petal category
pd.concat((PETAL_WIDTH_SERIES, petal_width_ef_binning), axis = 1)

    petal.width    petal.width
0           0.2  Sedikit Lebar
1           0.2  Sedikit Lebar
2           0.2  Sedikit Lebar
3           0.2  Sedikit Lebar
4           0.2  Sedikit Lebar
..          ...            ...
145         2.3   Sangat Lebar
146         1.9   Sangat Lebar
147         2.0   Sangat Lebar
148         2.3   Sangat Lebar
149         1.8   Sangat Lebar

[150 rows x 2 columns]

In [ ]:
# equal-frequency intervals binning with label
labelled_petal_width_ef_binning

Lebar            52
Sedikit Lebar    50
Sangat Lebar     48
Name: petal.width, dtype: int64

In [ ]:
# equal-frequency intervals without label
interval_petal_width_ef_binning

(0.867, 1.6]      52
(0.099, 0.867]    50
(1.6, 2.5]        48
Name: petal.width, dtype: int64

In [ ]:
# sepal length
# equal-frequency intervals

labels = ["Sedikit Lebar", "Lebar", "Sangat Lebar"]
amount_of_binning = len(labels)

sepal_length_ef_binning = pd.qcut(SEPAL_LENGTH_SERIES, amount_of_binning, labels)
labelled_sepal_length_ef_binning = sepal_length_ef_binning.value_counts()
interval_sepal_length_ef_binning = pd.qcut(SEPAL_LENGTH_SERIES, amount_of_binning).value_counts()

In [ ]:
# dataframe of sepal-length and sepal category
pd.concat((SEPAL_LENGTH_SERIES, sepal_length_ef_binning), axis=1)

    sepal.length   sepal.length
0            5.1  Sedikit Lebar
1            4.9  Sedikit Lebar
2            4.7  Sedikit Lebar
3            4.6  Sedikit Lebar
4            5.0  Sedikit Lebar
..           ...            ...
145          6.7   Sangat Lebar
146          6.3          Lebar
147          6.5   Sangat Lebar
148          6.2          Lebar
149          5.9          Lebar

[150 rows x 2 columns]

In [ ]:
# equal-frequency intervals binning with label
labelled_sepal_length_ef_binning

Lebar            56
Sedikit Lebar    52
Sangat Lebar     42
Name: sepal.length, dtype: int64

In [ ]:
# equal-frequency intervals out label
interval_sepal_length_ef_binning

(5.4, 6.3]                   56
(4.2989999999999995, 5.4]    52
(6.3, 7.9]                   42
Name: sepal.length, dtype: int64

In [ ]:
# petal lenght
# equal-frequency intervals

labels = ["Sedikit Lebar", "Lebar", "Sangat Lebar"]
amount_of_binning = len(labels)

petal_length_ef_binning = pd.qcut(PETAL_LENGTH_SERIES, amount_of_binning, labels)
labelled_petal_length_ef_binning = petal_length_ef_binning.value_counts()
interval_petal_length_ef_binning = pd.qcut(PETAL_LENGTH_SERIES, amount_of_binning).value_counts()

In [ ]:
# dataframe of petal-length and petal category
pd.concat((PETAL_LENGTH_SERIES, petal_length_ef_binning), axis=1)

    petal.length   petal.length
0            1.4  Sedikit Lebar
1            1.4  Sedikit Lebar
2            1.3  Sedikit Lebar
3            1.5  Sedikit Lebar
4            1.4  Sedikit Lebar
..           ...            ...
145          5.2   Sangat Lebar
146          5.0   Sangat Lebar
147          5.2   Sangat Lebar
148          5.4   Sangat Lebar
149          5.1   Sangat Lebar

[150 rows x 2 columns]

In [ ]:
# equal-frequency intervals binning with label
labelled_petal_length_ef_binning

Lebar            54
Sedikit Lebar    50
Sangat Lebar     46
Name: petal.length, dtype: int64

In [ ]:
# equal-frequency intervals out label
interval_petal_length_ef_binning

(2.633, 4.9]      54
(0.999, 2.633]    50
(4.9, 6.9]        46
Name: petal.length, dtype: int64

- Enthropy